### PR TITLE
 add basic support for ssb-revisions and ssb-threads

### PR DESCRIPTION
**Pull request by av8ta**
Also a fix for the branch property of PostMessage type: surprisingly a branch can be a string of the key of the message being replied to or a set (array) of message keys. I don't understand how a PostMessage reply can be to more than one message??? But since the log is full of many branches defined this way I've changed it to always output an array of branch keys.

### CODE REVIEW

**Comment by av8ta** [comment]
There's an error here. Fix is at https://github.com/av8ta/ssb-graphql-defaults/commit/c1ddffc511f3ae201ed09a5e08c08f26f8469cad

.... not sure how to roll it into this pull request on github sorry!

**Comment by av8ta** [comment]
> .... not sure how to roll it into this pull request on github sorry!

github has merged it automatically. Cool.

**Comment by luandro** [comment]
I don't have connection at home, so haven't had good time for dev this past week. I'll trust your PRs 👍

**Comment by av8ta** [comment]
Gosh! Thanks!

**Pull request merged**
